/* report.html — the approved report, printable.

   D-2: reports.body_md is rendered as PLAIN TEXT with textContent. Never
   markdown, never innerHTML. The text was assembled from what an agent
   wrote about what a researcher typed, so the only safe way to show it is
   as words. CSS keeps the line breaks (white-space: pre-wrap). */

guard(function (user) {
  var id = qs('id');

  function message(title, detail) {
    var host = clear($('#content'));
    var card = el('div', 'card empty');
    card.appendChild(el('div', 'mark', '—'));
    card.appendChild(el('h1', null, title));
    if (detail) card.appendChild(el('p', 'muted small', detail));
    var p = document.createElement('p');
    var a = el('a', 'btn btn-primary', 'Back to my missions');
    a.href = 'missions.html';
    p.appendChild(a);
    card.appendChild(p);
    host.appendChild(card);
  }

  if (!id) {
    message('Mission not found, or you do not have access to it');
    return;
  }

  $('#content').appendChild(el('p', 'muted small', 'Loading the report…'));

  Promise.all([Data.getMission(id), Data.getReport(id)]).then(function (res) {
    var mission = res[0], report = res[1];

    if (!mission) {
      message('Mission not found, or you do not have access to it');
      return;
    }
    if (!report) {
      message('No report has been generated for this mission yet',
        'Open the mission and press Generate Report once the six agents have finished.');
      return;
    }

    var host = clear($('#content'));

    var nav = el('div', 'section no-print');
    var navP = el('p', 'small');
    var back = el('a', null, '← Back to mission');
    back.href = 'mission.html?id=' + encodeURIComponent(mission.id);
    navP.appendChild(back);
    nav.appendChild(navP);
    host.appendChild(nav);

    var article = el('article', 'report');
    article.appendChild(el('h1', null, mission.title));

    var meta = el('p', 'meta');
    meta.appendChild(document.createTextNode((user.name || user.email) +
      (user.org ? ' · ' + user.org : '')));
    meta.appendChild(document.createElement('br'));
    meta.appendChild(document.createTextNode('Approved ' + fmtDateTime(report.approvedAt) + ' · Mission ID '));
    meta.appendChild(el('span', 'mono', mission.id));
    article.appendChild(meta);

    article.appendChild(el('hr', 'rule'));

    // THE WHOLE REPORT, AS TEXT. One line, and it is the reason a report
    // full of agent-written prose cannot run script in this page.
    article.appendChild(el('div', 'report-body', report.bodyMd));

    article.appendChild(el('hr', 'rule'));
    article.appendChild(el('p', 'meta',
      'Generated by KuwaitSat-1 Mission Hub. Sample data — not for operational use.'));
    host.appendChild(article);

    var row = el('div', 'btn-row no-print');
    row.style.marginTop = '20px';
    var print = el('button', 'btn btn-primary', 'Print / Save as PDF');
    print.type = 'button';
    print.addEventListener('click', function () { window.print(); });
    row.appendChild(print);
    var missions = el('a', 'btn btn-ghost', 'My missions');
    missions.href = 'missions.html';
    row.appendChild(missions);
    host.appendChild(row);

  }).catch(function (err) {
    message('The report could not be loaded', failMessage(err, 'Loading the report'));
  });
});
